"use client"

import { useState } from "react"
import { Eye, MoreHorizontal, Pencil, Trash2 } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { getStockClassName, MappingBadge, SupplierMappingStatusBadge } from "./inventory-status"
import type { Product } from "./types"

const headers = ["Vendor SKU","Product Name","Brand","OEM","Stock","Price","Mapping","Status","Product state","Vehicles","Actions"]
export function InventoryProductsTable({ products, onEditProduct, onDeleteProduct, onUpgradePlan }: { products: readonly Product[]; onEditProduct: (product: Product) => void; onDeleteProduct: (product: Product) => Promise<void>; onUpgradePlan: () => void }) {
  const [selected, setSelected] = useState<Product | null>(null)
  const [deleting, setDeleting] = useState<Product | null>(null)
  const [deleteError, setDeleteError] = useState<string | null>(null)
  return <><Card className="surface-card w-full min-w-0 overflow-hidden rounded-sm py-0 shadow-none"><div className="w-full overflow-x-auto"><Table><TableHeader><TableRow className="bg-brand-surface">{headers.map((header) => <TableHead key={header} className="min-w-[120px] px-6 py-4 text-brand-muted">{header}</TableHead>)}</TableRow></TableHeader><TableBody>
    {!products.length ? <TableRow><TableCell colSpan={headers.length} className="px-6 py-10 text-center text-brand-muted">No parts added yet. Use Add Single Product or Import Excel.</TableCell></TableRow> : null}
    {products.map((product) => <TableRow key={product.id ?? product.partNumber} className={`border-b border-border ${product.isActive ? "hover:bg-brand-panel-strong" : "bg-muted/30 text-muted-foreground"}`}><TableCell className="px-6 py-4 font-medium text-primary">{product.vendorSku ?? product.partNumber}</TableCell><TableCell className="px-6 py-4">{product.productName}</TableCell><TableCell className="px-6 py-4">{product.brand}</TableCell><TableCell className="px-6 py-4">{product.oemNumber}</TableCell><TableCell className={`px-6 py-4 font-semibold ${getStockClassName(product.stock)}`}>{product.stock}</TableCell><TableCell className="px-6 py-4 font-semibold">{product.price}</TableCell><TableCell className="px-6 py-4"><MappingBadge mapping={product.mapping} /></TableCell><TableCell className="px-6 py-4"><SupplierMappingStatusBadge status={product.mappingStatus} /></TableCell><TableCell className="px-6 py-4"><span className={`rounded-full px-2 py-1 text-xs font-medium ${product.isActive ? "bg-emerald-500/10 text-emerald-600" : "bg-amber-500/10 text-amber-600"}`}>{product.isActive ? "Active" : "Inactive"}</span></TableCell><TableCell className="px-6 py-4">{product.vehicles}</TableCell><TableCell className="px-6 py-4"><DropdownMenu><DropdownMenuTrigger asChild><Button size="icon-sm" variant="ghost" aria-label={`Actions for ${product.productName}`}><MoreHorizontal /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuLabel>Product actions</DropdownMenuLabel><DropdownMenuItem onSelect={() => setSelected(product)}><Eye />View product</DropdownMenuItem>{product.isActive ? <DropdownMenuItem onSelect={() => onEditProduct(product)}><Pencil />Edit Product Master fields</DropdownMenuItem> : <DropdownMenuItem onSelect={onUpgradePlan}><Pencil />Upgrade plan to activate</DropdownMenuItem>}<DropdownMenuItem className="text-destructive focus:text-destructive" onSelect={() => { setDeleteError(null); setDeleting(product) }}><Trash2 />Delete product</DropdownMenuItem></DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}
  </TableBody></Table></div></Card>
  <Dialog open={!!selected} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-h-[90vh] overflow-y-auto rounded-sm bg-brand-panel sm:max-w-3xl"><DialogHeader><DialogTitle>{selected?.productName ?? "Product details"}</DialogTitle><DialogDescription>Your supplier offer and mapping information.</DialogDescription></DialogHeader>{selected ? <div className="grid gap-3 rounded-sm border border-border bg-brand-surface p-4 text-sm sm:grid-cols-2"><p><strong>SKU:</strong> {selected.vendorSku}</p><p><strong>Brand:</strong> {selected.brand}</p><p><strong>MPN:</strong> {selected.partNumber}</p><p><strong>OEM:</strong> {selected.oemNumber}</p><p><strong>Category:</strong> {selected.category}</p><p><strong>Stock:</strong> {selected.stock}</p><p><strong>Price:</strong> {selected.price}</p><p><strong>Mapping:</strong> {selected.mappingStatus}</p><p><strong>Product state:</strong> {selected.isActive ? "Active" : "Inactive"}</p><p><strong>Competitor:</strong> {[selected.competitorBrandName,selected.competitorPartNumber].filter(Boolean).join(" · ") || "-"}</p><p><strong>HS code:</strong> {selected.hsCode ?? "-"}</p>{selected.planSuspensionReason ? <p className="sm:col-span-2 text-brand-warning"><strong>Plan note:</strong> {selected.planSuspensionReason}</p> : null}{selected.mappingError ? <p className="sm:col-span-2 text-brand-warning"><strong>Mapping note:</strong> {selected.mappingError}</p> : null}</div> : null}</DialogContent></Dialog>
  <Dialog open={!!deleting} onOpenChange={(open) => { if (!open) setDeleting(null) }}><DialogContent className="rounded-sm bg-brand-panel"><DialogHeader><DialogTitle>Delete product?</DialogTitle><DialogDescription>{deleting?.productName} will be permanently removed from your supplier inventory. This cannot be undone.</DialogDescription></DialogHeader>{deleteError ? <p className="text-sm text-destructive">{deleteError}</p> : null}<DialogFooter><Button type="button" variant="outline" onClick={() => setDeleting(null)}>Cancel</Button><Button type="button" variant="destructive" disabled={!deleting} onClick={async () => { if (!deleting) return; try { await onDeleteProduct(deleting); setDeleting(null) } catch (error) { setDeleteError(error instanceof Error ? error.message : "Unable to delete product") } }}>Delete product</Button></DialogFooter></DialogContent></Dialog>
  </>
}
